### ISSUE TITLE
GitHub Action setup documentation seems outdated

### ISSUE THREAD

**Issue by cchantep** [sbt/website#1275]
https://github.com/sbt/website/blob/17eb2924af58bf1eb62dfbc67e3073ae4177eb67/src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/04-GitHub-Actions-with-sbt.md?plain=1#L50

`sbt: command not found`

https://github.com/scala-ts/scala-ts/actions/runs/12690744241/job/35372261756?pr=2412#step:5:8

```yaml
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Set up JDK 1.8'
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        cache: sbt

    - name: 'Coursier cache'
      uses: coursier/cache-action@v5
      with:
        extraKey: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - name: 'Compile'
      run: 'sbt ...'
```
